create table CLIENTES(
  CLIENTE_ID          NUMBER(10) NOT NULL,
  NOME                VARCHAR2(20) NOT NULL,
  SEXO                CHAR(1) NOT NULL,
  CPF                 VARCHAR(14) NOT NULL,
  TELEFONE            VARCHAR(8) NOT NULL,
  DATA_HORA_CADASTRO  DATE NOT NULL,
  DATA_HORA_ALTERACAO DATE NOT NULL
);